// Copyright 2024 The Gitea Authors. All rights reserved.
// SPDX-License-Identifier: MIT

package apex

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net/url"
	"path/filepath"
	"sort"
	"strings"

	packages_model "forgejo.org/models/packages"
	user_model "forgejo.org/models/user"
	packages_module "forgejo.org/modules/packages"
	apex_module "forgejo.org/modules/packages/apex"
	"forgejo.org/modules/setting"
	"forgejo.org/modules/sync"
	"forgejo.org/modules/util"
	packages_service "forgejo.org/services/packages"

	"github.com/ProtonMail/go-crypto/openpgp"
	"github.com/ProtonMail/go-crypto/openpgp/armor"
	"github.com/ProtonMail/go-crypto/openpgp/packet"
)

var locker = sync.NewExclusivePool()

func GetOrCreateRepositoryVersion(ctx context.Context, ownerID int64) (*packages_model.PackageVersion, error) {
	return packages_service.GetOrCreateInternalPackageVersion(ctx, ownerID, packages_model.TypeApex, apex_module.RepositoryPackage, apex_module.RepositoryVersion)
}

func BuildAllRepositoryFiles(ctx context.Context, ownerID int64) error {
	pv, err := GetOrCreateRepositoryVersion(ctx, ownerID)
	if err != nil {
		return err
	}
	// remove old db files
	pfs, err := packages_model.GetFilesByVersionID(ctx, pv.ID)
	if err != nil {
		return err
	}
	for _, pf := range pfs {
		if fileArch, ok := strings.CutSuffix(pf.Name, ".db"); ok {
			if err := BuildApexDB(ctx, ownerID, pf.CompositeKey, fileArch); err != nil {
				return err
			}
		}
	}
	return nil
}

func BuildCustomRepositoryFiles(ctx context.Context, ownerID int64, disco string) error {
	pv, err := GetOrCreateRepositoryVersion(ctx, ownerID)
	if err != nil {
		return err
	}
	// remove old db files
	pfs, err := packages_model.GetFilesByVersionID(ctx, pv.ID)
	if err != nil {
		return err
	}
	for _, pf := range pfs {
		if strings.HasSuffix(pf.Name, ".db") && pf.CompositeKey == disco {
			if err := BuildApexDB(ctx, ownerID, pf.CompositeKey, ""); err != nil {
				return err
			}
			break
		}
	}
	return nil
}

func NewFileSign(ctx context.Context, ownerID int64, input io.Reader) (*packages_module.HashedBuffer, error) {
	// If no signature is specified, it will be generated by Gitea.
	priv, _, err := GetOrCreateKeyPair(ctx, ownerID)
	if err != nil {
		return nil, err
	}
	block, err := armor.Decode(strings.NewReader(priv))
	if err != nil {
		return nil, err
	}
	e, err := openpgp.ReadEntity(packet.NewReader(block.Body))
	if err != nil {
		return nil, err
	}
	pkgSig, err := packages_module.NewHashedBuffer()
	if err != nil {
		return nil, err
	}
	defer pkgSig.Close()
	if err := openpgp.DetachSign(pkgSig, e, input, nil); err != nil {
		return nil, err
	}
	return pkgSig, nil
}

// BuildApexDB Create db signature cache
func BuildApexDB(ctx context.Context, ownerID int64, group, _ string) error {
	key := fmt.Sprintf("pkg_%d_apex_db_%s", ownerID, group)
	locker.CheckIn(key)
	defer locker.CheckOut(key)
	pv, err := GetOrCreateRepositoryVersion(ctx, ownerID)
	if err != nil {
		return err
	}
	// Old DB files are intentionally NOT deleted here to prevent downtime.
	// AddFileToPackageVersionInternal with OverwriteExisting: true handles the atomic replacement.

	db, providersDB, err := createDB(ctx, ownerID, group)
	if err != nil {
		if errors.Is(err, io.EOF) {
			return deleteRepositoryFiles(ctx, pv, group)
		}
		return err
	}
	defer db.Close()
	defer providersDB.Close()

	// Create db signature cache
	_, err = db.Seek(0, io.SeekStart)
	if err != nil {
		return err
	}
	_, err = providersDB.Seek(0, io.SeekStart)
	if err != nil {
		return err
	}
	sig, err := NewFileSign(ctx, ownerID, db)
	if err != nil {
		return err
	}
	defer sig.Close()

	// Rewind db after NewFileSign consumes it
	_, err = db.Seek(0, io.SeekStart)
	if err != nil {
		return err
	}

	for name, data := range map[string]*packages_module.HashedBuffer{
		fmt.Sprintf("%s.db", group):        db,
		fmt.Sprintf("%s.db.sig", group):    sig,
		fmt.Sprintf("%s.providers", group): providersDB,
	} {
		_, err = packages_service.AddFileToPackageVersionInternal(ctx, pv, &packages_service.PackageFileCreationInfo{
			PackageFileInfo: packages_service.PackageFileInfo{
				Filename:     name,
				CompositeKey: group,
			},
			Creator:           user_model.NewGhostUser(),
			Data:              data,
			IsLead:            false,
			OverwriteExisting: true,
		})
		if err != nil {
			return err
		}
	}
	return nil
}

func deleteRepositoryFiles(ctx context.Context, pv *packages_model.PackageVersion, group string) error {
	pfs, err := packages_model.GetFilesByVersionID(ctx, pv.ID)
	if err != nil {
		return err
	}

	filenames := map[string]struct{}{
		fmt.Sprintf("%s.db", group):        {},
		fmt.Sprintf("%s.db.sig", group):    {},
		fmt.Sprintf("%s.files", group):     {},
		fmt.Sprintf("%s.providers", group): {},
	}
	for _, pf := range pfs {
		if pf.CompositeKey != group {
			continue
		}
		if _, ok := filenames[pf.Name]; !ok {
			continue
		}
		if err := packages_service.DeletePackageFile(ctx, pf); err != nil {
			return err
		}
	}
	return nil
}

func createDB(ctx context.Context, ownerID int64, group string) (*packages_module.HashedBuffer, *packages_module.HashedBuffer, error) {
	pkgs, err := packages_model.GetPackagesByType(ctx, ownerID, packages_model.TypeApex)
	if err != nil {
		return nil, nil, err
	}
	if len(pkgs) == 0 {
		return nil, nil, io.EOF
	}
	db, err := packages_module.NewHashedBuffer()
	if err != nil {
		return nil, nil, err
	}

	providersDB, err := packages_module.NewHashedBuffer()
	if err != nil {
		db.Close()
		return nil, nil, err
	}
	keepOpen := false
	defer func() {
		if !keepOpen {
			db.Close()
			providersDB.Close()
		}
	}()

	count := 0
	providerSet := make(map[string]struct{})
	for _, pkg := range pkgs {
		versions, err := packages_model.GetVersionsByPackageName(
			ctx, ownerID, packages_model.TypeApex, pkg.Name,
		)
		if err != nil {
			return nil, nil, err
		}
		sort.Slice(versions, func(i, j int) bool {
			return versions[i].CreatedUnix > versions[j].CreatedUnix
		})

		for _, ver := range versions {
			files, err := packages_model.GetFilesByVersionID(ctx, ver.ID)
			if err != nil {
				return nil, nil, err
			}
			for _, file := range files {
				ext := filepath.Ext(file.Name)
				if file.CompositeKey != group || ext == "" || ext == ".db" || ext == ".sig" {
					continue
				}
				if !strings.HasSuffix(file.Name, ".apex") && !strings.HasSuffix(file.Name, ".capex") {
					continue
				}

				properties, err := packages_model.GetProperties(ctx, packages_model.PropertyTypeFile, file.ID)
				if err != nil {
					return nil, nil, err
				}
				getProperty := func(propName string) string {
					for _, property := range properties {
						if property.Name == propName {
							return property.Value
						}
					}
					return ""
				}

				blob, err := packages_model.GetBlobByID(ctx, file.BlobID)
				if err != nil {
					return nil, nil, err
				}

				fileArch := getProperty(apex_module.PropertyArch)
				microArch := getProperty(apex_module.PropertyMicroArch)
				apiLevel := getProperty(apex_module.PropertyAPILevel)

				if apiLevel == "" {
					apiLevel = "29" // fallback if not available
				}
				if microArch == "" {
					microArch = "1"
				}

				pkgType := "apex"
				if strings.HasSuffix(file.Name, ".capex") {
					pkgType = "capex"
				}

				line := fmt.Sprintf("%s %s %s %s %s %d %s\n", pkg.Name, fileArch, microArch, apiLevel, ver.Version, blob.Size, pkgType)
				if _, err := db.Write([]byte(line)); err != nil {
					return nil, nil, err
				}

				// Providers logic
				provides := getProperty(apex_module.PropertyProvides)
				if provides != "" {
					for prov := range strings.SplitSeq(provides, "\n") {
						if prov == "" {
							continue
						}
						line := fmt.Sprintf("%s %s %s %s %s %s\n", prov, fileArch, microArch, apiLevel, pkg.Name, ver.Version)
						providerSet[line] = struct{}{}
					}
				}

				count++
			}
		}
	}
	if count == 0 {
		return nil, nil, io.EOF
	}

	// Write providers file
	providerLines := make([]string, 0, len(providerSet))
	for line := range providerSet {
		providerLines = append(providerLines, line)
	}
	sort.Strings(providerLines)
	for _, line := range providerLines {
		if _, err := providersDB.Write([]byte(line)); err != nil {
			return nil, nil, err
		}
	}

	keepOpen = true
	return db, providersDB, nil
}

// GetPackageFile Get data related to provided filename and distribution, for package files
// update download counter.
func GetPackageFile(ctx context.Context, group, file string, ownerID int64) (io.ReadSeekCloser, *url.URL, *packages_model.PackageFile, error) {
	fileParts := strings.Split(file, "/")
	if len(fileParts) < 4 {
		return nil, nil, nil, errors.New("invalid file format")
	}

	orgStartIndex := 2
	if strings.HasPrefix(fileParts[1], "v") {
		orgStartIndex = 3
	}

	if len(fileParts) <= orgStartIndex+1 {
		return nil, nil, nil, errors.New("invalid file format: missing package name or version")
	}

	verFile := fileParts[len(fileParts)-1]
	pkgVer := strings.TrimSuffix(verFile, ".apex")
	pkgVer = strings.TrimSuffix(pkgVer, ".capex")
	pkgVer = strings.TrimSuffix(pkgVer, ".sig")

	orgEndIndex := len(fileParts) - 1
	if len(fileParts) > orgStartIndex+2 && fileParts[len(fileParts)-2] == pkgVer {
		orgEndIndex = len(fileParts) - 2
	}

	orgPathParts := fileParts[orgStartIndex:orgEndIndex]
	pkgName := strings.Join(orgPathParts, ".")
	version, err := packages_model.GetVersionByNameAndVersion(ctx, ownerID, packages_model.TypeApex, pkgName, pkgVer)
	if err != nil {
		return nil, nil, nil, err
	}

	pkgFile, err := packages_model.GetFileForVersionByName(ctx, version.ID, file, group)
	if err != nil {
		return nil, nil, nil, err
	}

	return packages_service.GetPackageFileStream(ctx, pkgFile)
}

func GetPackageDBFile(ctx context.Context, ownerID int64, group, file string, sigFile bool) (io.ReadSeekCloser, *url.URL, *packages_model.PackageFile, error) {
	pv, err := GetOrCreateRepositoryVersion(ctx, ownerID)
	if err != nil {
		return nil, nil, nil, err
	}

	pkgFile, err := packages_model.GetFileForVersionByName(ctx, pv.ID, file, group)
	if errors.Is(err, util.ErrNotExist) {
		fallbackName := fmt.Sprintf("%s.db", group)
		if sigFile {
			fallbackName = fmt.Sprintf("%s.db.sig", group)
		}
		pkgFile, err = packages_model.GetFileForVersionByName(ctx, pv.ID, fallbackName, group)
	}
	if err != nil {
		return nil, nil, nil, err
	}
	return packages_service.GetPackageFileStream(ctx, pkgFile)
}

// GetOrCreateKeyPair gets or creates the PGP keys used to sign repository metadata files
func GetOrCreateKeyPair(ctx context.Context, ownerID int64) (string, string, error) {
	priv, err := user_model.GetSetting(ctx, ownerID, apex_module.SettingKeyPrivate)
	if err != nil && !errors.Is(err, util.ErrNotExist) {
		return "", "", err
	}

	pub, err := user_model.GetSetting(ctx, ownerID, apex_module.SettingKeyPublic)
	if err != nil && !errors.Is(err, util.ErrNotExist) {
		return "", "", err
	}

	if priv == "" || pub == "" {
		user, err := user_model.GetUserByID(ctx, ownerID)
		if err != nil && !errors.Is(err, util.ErrNotExist) {
			return "", "", err
		}

		priv, pub, err = generateKeypair(user.Name)
		if err != nil {
			return "", "", err
		}

		if err := user_model.SetUserSetting(ctx, ownerID, apex_module.SettingKeyPrivate, priv); err != nil {
			return "", "", err
		}

		if err := user_model.SetUserSetting(ctx, ownerID, apex_module.SettingKeyPublic, pub); err != nil {
			return "", "", err
		}
	}

	return priv, pub, nil
}

func generateKeypair(owner string) (string, string, error) {
	e, err := openpgp.NewEntity(
		owner,
		"Arch Package signature only",
		fmt.Sprintf("%s@noreply.%s", owner, setting.Packages.RegistryHost), &packet.Config{
			RSABits: 4096,
		})
	if err != nil {
		return "", "", err
	}

	var priv strings.Builder
	var pub strings.Builder

	w, err := armor.Encode(&priv, openpgp.PrivateKeyType, nil)
	if err != nil {
		return "", "", err
	}
	if err := e.SerializePrivate(w, nil); err != nil {
		return "", "", err
	}
	w.Close()

	w, err = armor.Encode(&pub, openpgp.PublicKeyType, nil)
	if err != nil {
		return "", "", err
	}
	if err := e.Serialize(w); err != nil {
		return "", "", err
	}
	w.Close()

	return priv.String(), pub.String(), nil
}
